version: '3.9'

services:

  modulo_envios:
    image: viniciussoares43/sigedam:modulo_envios_0.8
    container_name: modulo_envios
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      # coloque aqui suas vari√°veis de ambiente, se houver
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - sigedam-net

  modulo_usuarios:
    image: viniciussoares43/sigedam:modulo_usuarios_0.7
    container_name: modulo_usuarios
    restart: always
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/sigedam
      - QUARKUS_PROFILE=prod
      - TZ=America/Sao_Paulo
    ports:
      - "8002:8002"
    networks:
      - sigedam-net

  frontend:
    image: viniciussoares43/sigedam:front_0.9
    container_name: frontend
    restart: always
    ports:
      - "8080:8080"

  modulo_envios_worker:
    container_name: modulo_envios_worker
    image: viniciussoares43/sigedam:modulo_envios_0.8
    restart: always
    command: python -u -m src.consumers.notification_consumer
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
    depends_on:
      - redis
      - modulo_usuarios
    networks:
      - sigedam-net

  db:
    image: postgres:15-alpine
    container_name: sigedam_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - sigedam-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sigedam-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sigedam-net

volumes:
  redis_data:
  pg_data:

networks:
  sigedam-net:
    driver: bridge
